[project]
name = "fraud-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wakeel Ahmad", email = "157325160+wakeelkhan62@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "lightgbm>=4.7.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
fraud-detection = "fraud_detection:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
